[package]
name = "solver"
version = "0.1.0"
authors = ["Matthias Möller <m_moeller@live.de>"]
edition = "2018"

[dependencies]
varisat = "^0.2.1"
csv = "1.1"

[dependencies.clap]
version = "2.33.0"
default-features = false

[profile.release]
lto = true
opt-level=3